# Generated by Django 5.1.1 on 2024-10-04 05:50

import src.apps.category.domain.values_object
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryORM',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('cloth', 'Cloth'), ('accessory', 'Accessory')], default=src.apps.category.domain.values_object.CategoryEnum['Cloth'], max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
