# Generated by Django 5.1.1 on 2024-10-12 03:37

import uuid

import django.db.models.deletion
from django.db import migrations, models

import src.apps.product.domain.values_object.category
import src.apps.product.domain.values_object.gender


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandORM",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoryORM",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("cloth", "Cloth"), ("accessory", "Accessory")],
                        default=src.apps.product.domain.values_object.category.CategoryEnum[
                            "Cloth"
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ColorORM",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlaceSellORM",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SizeORM",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductORM",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unisex", "Unisex"),
                        ],
                        default=src.apps.product.domain.values_object.gender.GenderEnum[
                            "Unisex"
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("sold", models.PositiveIntegerField(default=0)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products_brand",
                        to="product.brandorm",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="product.categoryorm",
                    ),
                ),
                (
                    "color",
                    models.ManyToManyField(
                        related_name="products_color", to="product.colororm"
                    ),
                ),
                (
                    "place_sell",
                    models.ManyToManyField(
                        related_name="products_place_sell", to="product.placesellorm"
                    ),
                ),
                (
                    "size",
                    models.ManyToManyField(
                        related_name="products_size", to="product.sizeorm"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
