# Generated by Django 5.1.1 on 2024-10-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorm',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productorm',
            name='place_sell',
        ),
        migrations.RemoveField(
            model_name='productorm',
            name='size',
        ),
        migrations.AlterField(
            model_name='productorm',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productorm',
            name='color',
            field=models.ManyToManyField(related_name='products_color', to='product.colororm'),
        ),
        migrations.AddField(
            model_name='productorm',
            name='place_sell',
            field=models.ManyToManyField(related_name='products_place_sell', to='product.placesellorm'),
        ),
        migrations.AddField(
            model_name='productorm',
            name='size',
            field=models.ManyToManyField(related_name='products_size', to='product.sizeorm'),
        ),
    ]
